services:
  keybr:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./.docker-data:/root/.local/state/keybr
      - ./.env:/etc/keybr/env:ro
    restart: unless-stopped